### ISSUE TITLE
Could not find a face that downscales correctly within epsilon

### ISSUE THREAD

**Issue by manyone** [tg-bomze/Face-Depixelizer#12]
i keep getting that message even if my uploaded is square - i get the message whether the photo is unretouched, or is pixelated via photoshop pixelate effect option.  what should the input be - unretouched? or pixelated?  i was also careful about fitting my head inside the outline but it keeps returning with above message

**Comment by Acurisu** [comment]
I urge you to check older issues before opening a new one.
Your issue has already been addressed. ([see](https://github.com/tg-bomze/Face-Depixelizer/issues/7#issuecomment-647527110))

**Comment by manyone** [comment]
thank you.manny

    On Wednesday, June 24, 2020, 2:47:52 PM PDT, Acurisu <notifications@github.com> wrote:  
 
 


I urge you to check older issues before opening a new one.
Your issue has already been addressed. (see)

**Comment by tg-bomze** [comment]
fixed it
