### ISSUE TITLE
Doesn't work – confusing instructions

### ISSUE THREAD

**Issue by realpixelcode** [tg-bomze/Face-Depixelizer#6]
How to use Face Depixelizer properly? The instructions tell me to click on the "Let's Rock!" button but every time I get the error:

```
MessageError                              Traceback (most recent call last)
<ipython-input-7-af0d780e3ec8> in <module>()
     46   get_ipython().system('rm -rf /content/pulse/input/face.png')
     47   clear_output()
---> 48   uploaded = files.upload()
     49   for fn in uploaded.keys():
     50     print('User uploaded file "{name}" with length {length} bytes'.format(

2 frames
/usr/local/lib/python3.6/dist-packages/google/colab/_message.py in read_reply_from_input(message_id, timeout_sec)
    104         reply.get('colab_msg_id') == message_id):
    105       if 'error' in reply:
--> 106         raise MessageError(reply['error'])
    107       return reply.get('data', None)
    108 

MessageError: TypeError: Cannot read property '_uploadFiles' of undefined
```

Why is the "Choose a file" button deactivated? Is it a problem regarding the daily limit?

**Comment by woctezuma** [comment]
Click here.

![Where to click](https://i.imgur.com/YKGVS3M.png)

If this box is ticked:

![Box to tick the first time](https://i.imgur.com/amQZPI0.png)

Then you will see an upload button:

![Upload button](https://i.imgur.com/lSsa8Xm.png)

Upload your image. Once the program has finished running, you will see something like this:

![Finished](https://i.imgur.com/gGpCN7B.png)

Click here to download the image:

![Download](https://i.imgur.com/bqXUMXW.png)

**Comment by realpixelcode** [comment]
Well, when I click "Run", I do see an upload button but it is always deactivated.

![ezgif-1-01f7b7d70862](https://user-images.githubusercontent.com/52963327/85313176-55c91100-b4a7-11ea-8584-e185a3bfbaf5.gif)

**Comment by tg-bomze** [comment]
@realpixelcode 
![image](https://user-images.githubusercontent.com/48222107/85315405-351fac00-b4e5-11ea-94ba-a1ffc36a1638.png)

**Comment by realpixelcode** [comment]
@tg-bomze 
I tried it over and over again (minimum 20 times) but it keeps failing.
