### ISSUE TITLE
Always get "Could not find a face that downscales correctly within epsilon"

### ISSUE THREAD

**Issue by createmomo** [tg-bomze/Face-Depixelizer#7]
Thank you very much for the nice repository. I tried several pics, but I always get this error:
'''
Estimated Runtime: 29s.

Loading Synthesis Network
Optimizing
BEST (100) | L2: 0.0053 | GEOCROSS: 3.1139 | TOTAL: 0.6826 | time: 57.3 | it/s: 1.75 | batchsize: 1
Could not find a face that downscales correctly within epsilon

[Errno 2] No such file or directory: '/content/pulse/runs/face.png'
'''

Could you please point out a direction which I could work on to solve this problem?

**Comment by Acurisu** [comment]
**Solution**
Increase the steps or try a different resolution (if that's not possible you can upscale it for example bicubic).

You could however also set the `-eps` flag to a big enough value when running PULSE.

@tg-bomze I suggest adding a new parameter `epsilon = 2e-3 #@param {type:"number"}`.

**Why this happens**
After PULSE generates a result it checks whether the downloss is within `eps` (epsilon). If not then it will print the error message as the result is "too bad". This check was introduced in [Pulse Commit ece9211](https://github.com/adamian98/pulse/commit/ece9211c6448d3bca6c1d8c106ecfbf2e8eaed0f).

**Current state**
Some people over at PULSE are thinking it would be better to remove this check again as "we generally just want to see the best result achieved". ([source](https://github.com/adamian98/pulse/issues/19#issuecomment-647505570))

**Comment by woctezuma** [comment]
I can confirm. I encountered the issue with the default parameters, and increasing the steps from 100 to 500 solved the issue.

**Comment by createmomo** [comment]
Hi @Acurisu and @woctezuma , thank you very much for your kind reply! Yes, all the suggested solutions fixed the problem. :)

**Comment by ben74** [comment]
Damn that's what all those forks are made for ?
